name: fintech
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  modal_bottom_sheet: ^3.0.0
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.3.0
  rename: ^3.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  ios: true
  android: true
  image_path: "lib/Illustrations/AppIcon2.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Geo
      fonts:
        - asset: assets/fonts/Geo-Regular.ttf
        - asset: assets/fonts/Geo-Italic.ttf
          weight: 700
  assets:
    - lib/Illustrations/
